# Generated by Django 5.2.9 on 2025-12-30 21:42

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('recovery', 'Recovery'), ('easy', 'Easy'), ('tempo', 'Tempo'), ('threshold', 'Threshold'), ('interval', 'Interval'), ('repetition', 'Repetition')], max_length=20)),
                ('min_pace_min_per_km', models.DecimalField(decimal_places=2, help_text='Minimum pace in minutes per kilometer (e.g., 5.50 = 5:30/km)', max_digits=5)),
                ('max_pace_min_per_km', models.DecimalField(decimal_places=2, help_text='Maximum pace in minutes per kilometer', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#808080', help_text='Hex color code for calendar display (e.g., #FF5733)', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pace_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['min_pace_min_per_km'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('workout_type', models.CharField(choices=[('easy', 'Easy Run'), ('long', 'Long Run'), ('tempo', 'Tempo Run'), ('interval', 'Interval Training'), ('recovery', 'Recovery Run'), ('rest', 'Rest Day')], max_length=20)),
                ('target_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_duration', models.DurationField(blank=True, help_text='Target workout duration', null=True)),
                ('target_pace_min_per_km', models.DecimalField(blank=True, decimal_places=2, help_text='Target pace in minutes per kilometer', max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('order_in_day', models.PositiveSmallIntegerField(default=1, help_text='Order if multiple workouts on same day')),
                ('pace_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_workouts', to='training.pacezone')),
            ],
            options={
                'ordering': ['week', 'day_of_week', 'order_in_day'],
            },
        ),
        migrations.CreateModel(
            name='CompletedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('actual_distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_duration', models.DurationField()),
                ('average_pace_min_per_km', models.DecimalField(decimal_places=2, help_text='Average pace in minutes per kilometer', max_digits=5)),
                ('average_heart_rate', models.PositiveIntegerField(blank=True, help_text='Average heart rate in BPM', null=True)),
                ('elevation_gain_m', models.DecimalField(blank=True, decimal_places=2, help_text='Total elevation gain in meters', max_digits=7, null=True)),
                ('route', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='GPS route as LineString geometry', null=True, srid=4326)),
                ('gpx_file', models.FileField(blank=True, null=True, upload_to='gpx_files/%Y/%m/')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('gpx_upload', 'GPX Upload'), ('strava', 'Strava Import')], default='manual', max_length=20)),
                ('strava_activity_id', models.BigIntegerField(blank=True, help_text='Strava activity ID for deduplication', null=True, unique=True)),
                ('perceived_effort', models.PositiveSmallIntegerField(blank=True, help_text='Perceived effort on 1-10 scale', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_workouts', to=settings.AUTH_USER_MODEL)),
                ('scheduled_workout', models.ForeignKey(blank=True, help_text='Linked scheduled workout (null for unplanned runs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='training.scheduledworkout')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(choices=[('half_marathon', 'Half Marathon'), ('full_marathon', 'Full Marathon')], max_length=20)),
                ('methodology', models.CharField(choices=[('custom', 'Custom'), ('pfitzinger', 'Pfitzinger'), ('hanson', 'Hanson'), ('80_20', '80/20')], default='custom', max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('target_race_date', models.DateField(blank=True, null=True)),
                ('goal_time', models.DurationField(blank=True, help_text='Target finish time (e.g., 3:30:00 for 3h 30m)', null=True)),
                ('is_template', models.BooleanField(default=False, help_text='If True, this plan can be used as a template for others')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('focus', models.CharField(choices=[('base', 'Base Building'), ('build', 'Build Phase'), ('peak', 'Peak Phase'), ('taper', 'Taper')], max_length=10)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Planned total distance for the week in kilometers', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='training.trainingplan')),
            ],
            options={
                'ordering': ['plan', 'week_number'],
            },
        ),
        migrations.AddField(
            model_name='scheduledworkout',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_workouts', to='training.trainingweek'),
        ),
        migrations.AddIndex(
            model_name='pacezone',
            index=models.Index(fields=['user', 'name'], name='training_pa_user_id_bf2d0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pacezone',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='completedworkout',
            index=models.Index(fields=['user', '-date'], name='training_co_user_id_9727de_idx'),
        ),
        migrations.AddIndex(
            model_name='completedworkout',
            index=models.Index(fields=['user', 'date'], name='training_co_user_id_6bf409_idx'),
        ),
        migrations.AddIndex(
            model_name='completedworkout',
            index=models.Index(fields=['strava_activity_id'], name='training_co_strava__905eda_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['user', '-created_at'], name='training_tr_user_id_d7597f_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['is_template'], name='training_tr_is_temp_829dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingweek',
            index=models.Index(fields=['plan', 'week_number'], name='training_tr_plan_id_662c3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingweek',
            unique_together={('plan', 'week_number')},
        ),
        migrations.AddIndex(
            model_name='scheduledworkout',
            index=models.Index(fields=['week', 'day_of_week'], name='training_sc_week_id_045829_idx'),
        ),
    ]
