# Generated by Django 5.2.9 on 2026-01-05 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_data', models.JSONField(default=list, help_text='Seconds from start')),
                ('distance_data', models.JSONField(default=list, help_text='Meters')),
                ('heartrate_data', models.JSONField(default=list, help_text='BPM (may contain nulls)')),
                ('velocity_data', models.JSONField(default=list, help_text='Meters per second')),
                ('altitude_data', models.JSONField(default=list, help_text='Meters elevation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='training.completedworkout')),
            ],
            options={
                'verbose_name': 'Activity Stream',
                'verbose_name_plural': 'Activity Streams',
            },
        ),
    ]
