# Generated by Django 5.2.9 on 2026-01-05 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_add_activity_stream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFitnessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold_hr', models.PositiveIntegerField(blank=True, help_text='Lactate threshold heart rate in BPM', null=True)),
                ('threshold_pace', models.DecimalField(blank=True, decimal_places=2, help_text='Threshold pace in minutes per kilometer (e.g., 4.50 = 4:30/km)', max_digits=5, null=True)),
                ('target_weekly_tss', models.PositiveIntegerField(default=300, help_text='Target weekly Training Stress Score')),
                ('recovery_tsb_threshold', models.IntegerField(default=-20, help_text='TSB threshold below which recovery is recommended')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Fitness Settings',
                'verbose_name_plural': 'User Fitness Settings',
            },
        ),
        migrations.CreateModel(
            name='TrainingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('daily_tss', models.DecimalField(decimal_places=2, default=0, help_text='Training Stress Score for this day', max_digits=7)),
                ('atl', models.DecimalField(decimal_places=2, default=0, help_text='Acute Training Load (7-day exponentially weighted)', max_digits=7)),
                ('ctl', models.DecimalField(decimal_places=2, default=0, help_text='Chronic Training Load (42-day exponentially weighted)', max_digits=7)),
                ('tsb', models.DecimalField(decimal_places=2, default=0, help_text='Training Stress Balance (CTL - ATL)', max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='training_tr_user_id_13ad39_idx'), models.Index(fields=['user', 'date'], name='training_tr_user_id_86c6a8_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
