# Generated by Django 5.2.9 on 2026-01-05 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_add_training_load_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_type', models.CharField(choices=[('race_time', 'Race Time'), ('weekly_km', 'Weekly Distance'), ('monthly_km', 'Monthly Distance'), ('pace', 'Pace Improvement')], max_length=20)),
                ('title', models.CharField(help_text="Goal title (e.g., 'Sub-4 Marathon')", max_length=200)),
                ('race_distance', models.CharField(blank=True, choices=[('1k', '1K'), ('5k', '5K'), ('10k', '10K'), ('half', 'Half Marathon'), ('full', 'Marathon'), ('custom', 'Custom Distance')], max_length=10, null=True)),
                ('target_time', models.DurationField(blank=True, help_text='Target time for race goals', null=True)),
                ('target_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Target distance in km', max_digits=7, null=True)),
                ('target_pace', models.DecimalField(blank=True, decimal_places=2, help_text='Target pace in min/km', max_digits=5, null=True)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current progress value', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('expired', 'Expired'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='training_go_user_id_24ff3d_idx'), models.Index(fields=['user', '-created_at'], name='training_go_user_id_89745e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance', models.CharField(choices=[('1k', '1K'), ('5k', '5K'), ('10k', '10K'), ('half', 'Half Marathon'), ('full', 'Marathon'), ('custom', 'Custom Distance')], max_length=10)),
                ('custom_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km for custom records', max_digits=6, null=True)),
                ('time', models.DurationField(help_text='Personal record time')),
                ('date', models.DateField()),
                ('pace_min_per_km', models.DecimalField(decimal_places=2, help_text='Average pace in minutes per kilometer', max_digits=5)),
                ('is_manual', models.BooleanField(default=False, help_text='True if manually entered (not auto-detected)')),
                ('source_workout', models.ForeignKey(blank=True, help_text='Workout that set this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_records', to='training.completedworkout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['distance', '-created_at'],
                'indexes': [models.Index(fields=['user', 'distance'], name='training_pe_user_id_d62b34_idx'), models.Index(fields=['user', '-date'], name='training_pe_user_id_c804a1_idx')],
            },
        ),
    ]
