# Generated by Django 5.2.9 on 2025-12-30 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava_integration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StravaToken',
        ),
    ]
