# Generated by Django 5.2.9 on 2025-12-30 22:08

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='For age-graded performance calculations', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_distance_unit',
            field=models.CharField(choices=[('km', 'Kilometers'), ('mi', 'Miles')], default='km', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='strava_athlete_id',
            field=models.BigIntegerField(blank=True, help_text='Strava athlete ID for quick lookups', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='strava_profile_picture_url',
            field=models.URLField(blank=True, help_text='Strava profile picture URL', max_length=500),
        ),
        migrations.CreateModel(
            name='StravaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', encrypted_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_fields.fields.EncryptedTextField()),
                ('expires_at', models.DateTimeField()),
                ('scope', models.CharField(default='read,activity:read_all,profile:read_all', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strava_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strava token',
                'verbose_name_plural': 'Strava tokens',
            },
        ),
    ]
