# Generated by Django 5.2.9 on 2026-01-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_of_birth_user_preferred_distance_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravatoken',
            name='scope',
            field=models.CharField(default='read,read_all,activity:read_all', max_length=255),
        ),
    ]
