# Generated by Django 5.2.9 on 2026-01-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_stravatoken_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_strava_sync',
            field=models.DateTimeField(blank=True, help_text='Last time Strava activities were synced', null=True),
        ),
    ]
